name: "kubectl via gcloud"
description: "Issues kubectl commands with a kubeconfig exported via gcloud."
branding:
  icon: "anchor"
  color: "blue"
runs:
  using: "docker"
  image: 'docker://docker.io/statsig/kubectl-via-gcloud:latest'
